# Generated by Django 3.2.7 on 2021-09-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('joke', models.CharField(choices=[('fat', 'fat'), ('dumb', 'dump'), ('stupid', 'stupid'), ('no_joke', 'no_joke')], default='no_joke', max_length=30)),
            ],
        ),
    ]
